// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface FeatureStoryblok {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: any;
}

export interface GridStoryblok {
  columns?: (
    | FeatureStoryblok
    | GridStoryblok
    | ImageContentStoryblok
    | PageStoryblok
    | PageHeroStoryblok
    | TeaserStoryblok
    | TextContentStoryblok
  )[];
  component: "grid";
  _uid: string;
  [k: string]: any;
}

export interface AssetStoryblok {
  alt?: string;
  copyright?: string;
  id: number;
  filename: string;
  name: string;
  title?: string;
  focus?: string;
  [k: string]: any;
}

export interface RichtextStoryblok {
  type: string;
  content?: RichtextStoryblok[];
  marks?: RichtextStoryblok[];
  attrs?: any;
  text?: string;
  [k: string]: any;
}

export interface ImageContentStoryblok {
  image?: AssetStoryblok;
  content?: RichtextStoryblok;
  component: "image_content";
  _uid: string;
  [k: string]: any;
}

export interface PageStoryblok {
  body?: (ImageContentStoryblok | PageHeroStoryblok | TextContentStoryblok)[];
  component: "page";
  _uid: string;
  [k: string]: any;
}

export interface PageHeroStoryblok {
  image?: AssetStoryblok;
  component: "page_hero";
  _uid: string;
  [k: string]: any;
}

export interface TeaserStoryblok {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: any;
}

export interface TextContentStoryblok {
  content?: string;
  component: "text_content";
  _uid: string;
  [k: string]: any;
}
