import type { Metadata } from 'next';
import './globals.scss';
import Header from '@/components/shared/header';
import { Toaster } from '@/components/ui/toaster';
import { ReduxProvider } from '@/redux/provider';
import StoryblokProvider from '@/components/storyblok/provider';
import { sbInit } from '@/utils/SbInit';
import { accentFont, primaryFont } from '@/utils/fonts';
import Footer from '@/components/shared/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

sbInit();

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className={`${primaryFont.variable} ${accentFont.variable} font-default`}>
      <body>
        <ReduxProvider>
          <StoryblokProvider>
            <Header />
            <Toaster />
            {children}
            <Footer />
          </StoryblokProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
