import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/shared/header';
import { Toaster } from '@/components/ui/toaster';
import { ReduxProvider } from '@/redux/provider';
import StoryblokProvider from '@/components/storyblok/provider';
import { sbInit } from '@/utils/SbInit';
import { primaryFont } from '@/utils/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

sbInit();

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${primaryFont.className} font-test`}>
        <ReduxProvider>
          <StoryblokProvider>
            <Header />
            <Toaster />
            {children}
          </StoryblokProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
